export const Recipes = [{
    id: 1,
    title: "Pork Adobo",
    description: "This is a recipe post for Filipino Pork Adobo. It is a dish composed of pork slices cooked in soy sauce, vinegar, and garlic. There are version wherein onions are also added. Adobo is a popular dish in the Philippines, along with Sinigang. ",
    prep: "10 minutes",
    cook: "1 hour",
    ingredients: ['1.5 lbs pork belly',
        '1.5 tablespoons garlic',
        '3.75 dried bay leaves',
        '3 tablespoons vinegar',
        '0.38 cup soy sauce',
        '0.75 tablespoon peppercorn',
        '1.5 cups water',
        'Salt to taste',],
    instructions: ['Combine the pork belly, soy sauce, and garlic then marinade for at least 1 hour',
        'Heat the pot and put-in the marinated pork belly then cook for a few minutes',
        'Pour remaining marinade including garlic.',
        'Add water, whole pepper corn, and dried bay leaves then bring to a boil. Simmer for 40 minutes to 1 hour',
        'Put-in the vinegar and simmer for 12 to 15 minutes',
        'Add salt to taste',
        'Serve hot. Share and enjoy!'],
    notes: ['Pork belly is the most common cut of pork to use for adobo, but you can also use other cuts as long as it has some fat content. Fat makes the meat moist. I suggest using pork shoulder as an alternative cut.',
        "Filipino adobo won’t be the same without garlic. The more garlic I use, the better my adobo is (in my opinion). Crush the garlic using a mortar and pestle tool or the side of your knife before cooking. This ensures that the flavors are quickly extracted from it.",
        'Bay leaves or Laurel leaves is a must for this recipe. Dried bay leaves are the most commonly used due to its availability. Fresh bay leaves is good too.',
        'Use white vinegar. If this is not available, either cane or rice vinegar can be used as substitutes.',
        'I use Filipino brand soy sauce all the time. In my opinion, using other kinds of soy sauce affects the authentic flavor of the dish.',
        'Whole peppercorns are ideal. However, you can use cracked pepper or ground pepper for this recipe.'],
    nutritionInfo: '"Serving: 4g", "Calories: 1211kcal (61%)", "Carbohydrates: 5g (2%)", "Protein: 24g (48%)", "Fat: 120g (185%)", "Saturated Fat: 43g (215%)", "Cholesterol: 163mg (54%)", "Sodium: 1700mg (71%)", "Potassium: 530mg (15%)", "Fiber: 1g (4%)", "Vitamin A: 115IU (2%)", "Vitamin C: 2.5mg (3%)", "Calcium: 50mg (5%)", "Iron: 2.7mg (15%)"'
},
{
    id: 2,
    // image: require("./assets/yumkit-favicon-color.png"),
    title: "Chicken Afritada sa Gata",
    description: "Filipino chicken stew recipe wherein chicken is stewed in tomato sauce and coconut milk.",
    prep: "10 minutes",
    cook: "50 minutes",
    ingredients: ['3 lbs. chicken sliced into serving pieces',
        '30 grams Knorr Ginataang Gulay Recipe Mix',
        '0.75 Knorr Chicken Cube',
        '2.25 potatoes',
        '3 carrots',
        '2.25 bell peppers',
        '0.56 cup green peas',
        '0.75 onion chopped',
        '4.5 cloves garlic',
        '6 ounces tomato sauce',
        '6 hotdogs',
        '1.5 cups water',
        '2.25 tablespoons cooking oil',
        'Salt and ground black pepper to taste'],
    instructions: ['Heat oil in a pan. Saute garlic and onion.',
        'Add the chicken. Saute until it turns light brown in color.',
        'Add tomato sauce, hotdogs, and water. Let it boil.',
        'Combine Knorrr Ginataang Gulay Recipe Mix with 2 cups water. Mix well and then pour it into the pan. Cover and cook for 45 minutes using low heat.',
        'Add Knorr Chicken Cube, potatoes, and carrots. Cook for 8 minutes.',
        'Add the green peas and bell peppers. Cook for 3 minutes.',
        'Season with salt and ground black pepper.',
        'Serve with rice. Share and enjoy!'],
    nutritionInfo: '"Calories: 1421kcal (71%)", "Carbohydrates: 46g (15%)", "Protein: 99g (198%)", "Fat: 93g (143%)", "Saturated Fat: 25g (125%)", "Polyunsaturated Fat: 20g", "Monounsaturated Fat: 41g", "Trans Fat: 0.5g", "Cholesterol: 381mg (127%)", "Sodium: 1498mg (62%)", "Potassium: 1794mg (51%)", "Fiber: 11g (44%)", "Sugar: 12g (13%)", "Vitamin A: 14245IU (285%)", "Vitamin C: 144mg (175%)", "Calcium: 292mg (29%)", "Iron: 12mg (67%)"'
},
]